### PR TITLE
[SLAM] Support optional arguments with override methods

### PR DESCRIPTION
**Pull request by DonnaWuDongxia**
- support optional arugments by overriding methods for
  getOccupancyMap[Updates] and setInstanceOptions interfaces.
- remove unnecessary optional arguments for saveXXX interfaces
- make return value of saveXXX interfaces as void.
- modify related test cases.

### CODE REVIEW

**Comment by DonnaWuDongxia** [comment]
@halton @kenny-y @lisa0314 please help to review.

**Review by kenny-y — APPROVED** [review]
LGTM for the IDL change...

**Comment by halton** [comment]
@lisa0314 can I leverage your review on SLAM?

**Comment by lisa0314** [comment]
@kenny-y @halton , it seems good to me. Could you please help to merge it?

**Comment by halton** [comment]
> @kenny-y @halton , it seems good to me. Could you please help to merge it?

Next time, please give explicit LGTM.

**Pull request merged**
