### PR TITLE
[samples] add ocf realsense samples

### PR DESCRIPTION
**Pull request by wanghongjuan**
- add two samples for ocf realsense samples to this repository

### CODE REVIEW

**Comment by wanghongjuan** [comment]
@kenny-y Could you please take a look?

**Comment by DonnaWuDongxia** [comment]
@wanghongjuan there are some lint error in JavaScript files. I know we leveraged some UI files from PerC's native sample. Those files can be out of the lint scope, but we need to make sure the code made by ourselves should passed the lint tool.

**Comment by wanghongjuan** [comment]
@DonnaWuDongxia Thanks for your comment, I will format the code to conform the lint tool

**Comment by wanghongjuan** [comment]
@DonnaWuDongxia  I updated the code, please take a look. Thanks

**Comment by wanghongjuan** [comment]
@DonnaWuDongxia I fixed the lint error in js files, see detail information:
- Except js files in third-party, all files have been passed eslint
- For error: `Missing trailing comma`, when only one property or the last property is listed in a array
  doesn't need to add the trailing comma
- For `warning`: won't fix
- For error: `'xxx' is defined but never used`, this variable is used in other file
- For error: `'xxx' is assigned a value but never used`, this variable is used in other file

Meanwhile, I found one weird thing: Same code in different file, the checked result using eslint is different, one is an error, other is a warning.
view js

**Comment by DonnaWuDongxia** [comment]
@wanghongjuan Great work! I'm merging it.

**Pull request merged**
