### PR TITLE
Change module name in each source directories, to align with …

### LINKED ISSUE #129: Rename each Node.js module in source code
In `package.json` of each Node.js module, change the package name to align with the names used in https://www.npmjs.com/~kenny-yuan

image

### PR DESCRIPTION
**Pull request by kenny-y**
…npmjs.com module

Closes #129

### CODE REVIEW

**Review by halton — CHANGES_REQUESTED** [review]
LGTM if we keep the version untouched.

**Comment by kenny-y** [comment]
Versions were not seriously treated before npmjs publish.
And the change in this PR is to align with npmjs.com package.

image

**Comment by halton** [comment]
I suppose master can have different version, do not require match the npmjs registration. Otherwise, my understanding is wrong.

**Comment by kenny-y** [comment]
If we're using single repo, the version will be exactly the same one and there is tool to make the management easy.

For this multiple repo mode, I believe a same-version policy will reduce our maintenance efforts (e.g. bookkeeping of the version mapping table, etc.)

**Review by halton — APPROVED** [review]
LGTM

**Comment by halton** [comment]
Merge w/o waiting for trybot finish cause it won't break buildbot at all

**Pull request merged**
