### PR TITLE
Update the doc for set up enviroment

### PR DESCRIPTION
**Pull request by lisa0314**
@DonnaWuDongxia @kenny-y @tingshao PTAL.

### CODE REVIEW

**Comment by kenny-y** [comment]
I'll read this later and might come up with change suggestions.

**Comment by kenny-y** [comment]
Suggestions PR-ed to https://github.com/lisa0314/node-realsense-1

**Comment by kenny-y** [comment]
ZR300 preorder link: https://click.intel.com/intelr-realsensetm-development-kit-featuring-the-zr300.html

We can add it to camera section.

**Comment by lisa0314** [comment]
@kenny-y , thanks for your suggestions. PTAL.

**Pull request merged**
